import "./globals.css";
import Sidebar from "../components/Sidebar";
import Article from "../components/Article";
import Footer from "../components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body
        style={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          height: "100vh",
          backgroundColor: "#316094",
        }}
      >
        <div className="w-200px h-150px bg-[#000000] flex">
          {/* 사이드 바 */}
          <div className="flex-grow-[1]">
            <Sidebar />
          </div>
          {/* 메인 Article */}
          <div className="flex-grow-[2.5] m-[auto]">
            <Article />
            {children}
          </div>
          {/* 푸터 */}
          <div className="flex-grow-[1]">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
