import "./book.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
//export default function RootLayout({ children }) {

function BookLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body>{children}</body>
    </html>
  );
}

export default BookLayout;
